name: teste_flutter_crmall
description: Aplication for test in flutter interview.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  rxdart: ^0.25.0
  crypto: ^2.1.5
  carousel_slider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: Little Cupcakes
      fonts:
        - asset: assets/font/Little Cupcakes.ttf
          weight: 700

    - family: cream-DEMO
      fonts:
        - asset: assets/font/cream-DEMO.ttf
          weight: 700